### ISSUE TITLE
Qual o processo de scraping?

### ISSUE THREAD

**Issue by whaner** [luiseduardobr1/covid19-Ceara#1]
Como você está fazendo o scraping dos dados?

**Comment by luiseduardobr1** [comment]
Estou baixando pela API do integraSUS. Conferi os dados e batem com os do site da plataforma. Corrigi também um bug com os óbitos por município, segue código: https://github.com/luiseduardobr1/covid19-Ceara/blob/master/algoritmos/integrasus.py
